* numpy QuickStart練習主要來自於[scipy網站](https://docs.scipy.org/doc/numpy-dev/user/quickstart.html)

In [1]:
import numpy as np 

## Basic 
- arange
- shape 
- ndim 
- dtype
- itemsize
- size 

In [2]:
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [3]:
a.shape

(3, 5)

In [4]:
a.ndim

2

In [6]:
a.dtype.name

'int64'

In [7]:
a.itemsize

8

In [8]:
a.size

15

In [9]:
type(a)

numpy.ndarray

In [12]:
a.data

## Array creation 

In [14]:
a = np.array([2,3,4])
a

array([2, 3, 4])

In [15]:
a.dtype

dtype('int64')

In [16]:
b = np.array([2.1,2.2,3.3])
b

array([ 2.1,  2.2,  3.3])

In [17]:
b.dtype

dtype('float64')

In [19]:
c = np.array([[1,2],[3,4]],dtype='complex')
c

array([[ 1.+0.j,  2.+0.j],
       [ 3.+0.j,  4.+0.j]])

In [20]:
c.dtype

dtype('complex128')

In [22]:
d = np.zeros((3,4,2))
d

array([[[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]],

       [[ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.],
        [ 0.,  0.]]])

In [23]:
d.shape

(3, 4, 2)

In [24]:
d.ndim

3

In [26]:
np.ones((3,4),dtype=np.int16)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)

In [29]:
np.empty([2,3],dtype=int)

array([[              0,  93827439440000, 140323393666216],
       [ 93827439243504,               0,               0]])

In [30]:
np.arange(10,30,5)

array([10, 15, 20, 25])

In [31]:
np.arange(0,2,0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

In [32]:
np.linspace(0,2,9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [35]:
x = np.linspace(0,2*np.pi,100)
f = np.sin(x)

## Print Arrays

In [36]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [38]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [39]:
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [40]:
c = np.arange(24).reshape(2,3,4)
c

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [43]:
c[0,1,:]

array([4, 5, 6, 7])

In [48]:
np.arange(10000).reshape(100,100)

array([[   0,    1,    2, ...,   97,   98,   99],
       [ 100,  101,  102, ...,  197,  198,  199],
       [ 200,  201,  202, ...,  297,  298,  299],
       ..., 
       [9700, 9701, 9702, ..., 9797, 9798, 9799],
       [9800, 9801, 9802, ..., 9897, 9898, 9899],
       [9900, 9901, 9902, ..., 9997, 9998, 9999]])

## Basic operations

In [50]:
a = np.array([2,3,4,5])
b = np.arange(4)
print(a)
print(b)

[2 3 4 5]
[0 1 2 3]


In [51]:
a**2

array([ 4,  9, 16, 25])

In [52]:
print(b+2)

[2 3 4 5]


In [53]:
10*np.sin(a)

array([ 9.09297427,  1.41120008, -7.56802495, -9.58924275])

In [55]:
a < 3

array([ True, False, False, False], dtype=bool)

In [57]:
A = np.array([[1,2],
             [3,4]])
B = np.array([[2,3],
              [4,5]])
A*B # element-wise multiplication

array([[ 2,  6],
       [12, 20]])

In [58]:
A.dot(B) # matrix multiplication

array([[10, 13],
       [22, 29]])

In [59]:
np.dot(A,B)

array([[10, 13],
       [22, 29]])

In [60]:
np.dot(B,A)

array([[11, 16],
       [19, 28]])

In [64]:
a = np.ones((2,3),dtype=int)
b = np.random.random((2,3))
b

array([[ 0.23302406,  0.84933169,  0.46003348],
       [ 0.7519787 ,  0.8099214 ,  0.346407  ]])

In [65]:
a *= 3
a

array([[3, 3, 3],
       [3, 3, 3]])

In [66]:
b += a
b

array([[ 3.23302406,  3.84933169,  3.46003348],
       [ 3.7519787 ,  3.8099214 ,  3.346407  ]])

In [67]:
a += b

TypeError: Cannot cast ufunc add output from dtype('float64') to dtype('int64') with casting rule 'same_kind'

In [71]:
a = np.ones(3,dtype=np.int32)
b = np.linspace(0,np.pi,3)

In [73]:
b.dtype.name

'float64'

In [74]:
c = a+b 
c.dtype

dtype('float64')

In [76]:
a = np.random.random((3,4))
a.sum()

6.8787589612162927

In [78]:
a.min()

0.19701339456267719

In [79]:
a.max()

0.876914581757955

In [80]:
b = np.arange(12).reshape(3,4)
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [81]:
b.sum(axis=0) # sum of each column

array([12, 15, 18, 21])

In [82]:
b.sum(axis=1)

array([ 6, 22, 38])

In [83]:
b.min(axis=0)

array([0, 1, 2, 3])

In [84]:
b.max(axis=0)

array([ 8,  9, 10, 11])

In [85]:
b.cumsum(axis=1) # cumulative sum along each row

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

## Universal Function

In [86]:
B = np.arange(3)

In [88]:
np.exp(B)

array([ 1.        ,  2.71828183,  7.3890561 ])

In [89]:
np.sqrt(B)

array([ 0.        ,  1.        ,  1.41421356])

In [90]:
np.bincount(np.arange(10))

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [100]:
b = np.random.randint(0,3,5)
b

array([2, 1, 1, 0, 1])

In [107]:
np.bincount(b)

array([1, 3, 1])

In [111]:
func = lambda a:(a[0]+a[-1])/2
a = np.arange(12).reshape(2,6)
a

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11]])

In [112]:
np.apply_along_axis(func,1,a)

array([ 2.5,  8.5])

## Indexing ,slicing

In [113]:
a = np.arange(10)**3
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

In [114]:
a[2]

8

In [115]:
a[2:5]

array([ 8, 27, 64])

In [116]:
a[:6:2]

array([ 0,  8, 64])

In [117]:
a[:6:2]=-1000

In [118]:
a

array([-1000,     1, -1000,    27, -1000,   125,   216,   343,   512,   729])

In [119]:
a[::-1]

array([  729,   512,   343,   216,   125, -1000,    27, -1000,     1, -1000])

In [122]:
for i in a:
    print(i**(-1/3.))

nan
1.0
nan
0.333333333333
nan
0.2
0.166666666667
0.142857142857
0.125
0.111111111111


/home/ihong/anaconda3/lib/python3.5/site-packages/ipykernel/__main__.py:2: RuntimeWarning: invalid value encountered in power
  from ipykernel import kernelapp as app


In [123]:
def f(x,y):
    return 10*x+y
b = np.fromfunction?

In [127]:
b = np.fromfunction(lambda i,j:10*i+j,(3,3),dtype=int)
b

array([[ 0,  1,  2],
       [10, 11, 12],
       [20, 21, 22]])

In [128]:
b[:,1]

array([ 1, 11, 21])

In [129]:
b[0:2,:]

array([[ 0,  1,  2],
       [10, 11, 12]])

In [130]:
a = np.arange(12).reshape(2,3,2)
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [131]:
a[1,...]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [135]:
a[1,]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [136]:
a[1,:]

array([[ 6,  7],
       [ 8,  9],
       [10, 11]])

In [144]:
a[:,:,0]

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [143]:
a[...,0]

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [146]:
a

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [149]:
for row in b:
    print(row)

[0 1 2]
[10 11 12]
[20 21 22]


In [153]:
b.flatten()

array([ 0,  1,  2, 10, 11, 12, 20, 21, 22])

In [155]:
for e in b.flat:
    print(e)

0
1
2
10
11
12
20
21
22


# Shape manipulation
## changing the shape of array

In [178]:
a = np.floor(10*np.random.random(12).reshape(3,4))
print(a)

[[ 5.  1.  4.  0.]
 [ 6.  1.  6.  2.]
 [ 7.  3.  0.  8.]]


In [184]:
a.ravel() 

array([ 5.,  1.,  4.,  0.,  6.,  1.,  6.,  2.,  7.,  3.,  0.,  8.])

In [185]:
a.flatten()

array([ 5.,  1.,  4.,  0.,  6.,  1.,  6.,  2.,  7.,  3.,  0.,  8.])

In [186]:
a.reshape(6,2)

array([[ 5.,  1.],
       [ 4.,  0.],
       [ 6.,  1.],
       [ 6.,  2.],
       [ 7.,  3.],
       [ 0.,  8.]])

In [188]:
a.resize((6,2))

In [189]:
a

array([[ 5.,  1.],
       [ 4.,  0.],
       [ 6.,  1.],
       [ 6.,  2.],
       [ 7.,  3.],
       [ 0.,  8.]])

In [191]:
a.reshape(3,4)

array([[ 5.,  1.,  4.,  0.],
       [ 6.,  1.,  6.,  2.],
       [ 7.,  3.,  0.,  8.]])

In [193]:
a.reshape(3,-1)

array([[ 5.,  1.,  4.,  0.],
       [ 6.,  1.,  6.,  2.],
       [ 7.,  3.,  0.,  8.]])

## stacking different array

In [196]:
a = np.floor(10*np.random.random((2,2)))
a

array([[ 8.,  8.],
       [ 9.,  0.]])

In [197]:
b = np.floor(10*np.random.random((2,2)))
b

array([[ 5.,  3.],
       [ 3.,  2.]])

In [199]:
np.hstack((a,b))

array([[ 8.,  8.,  5.,  3.],
       [ 9.,  0.,  3.,  2.]])

In [200]:
np.vstack((a,b))

array([[ 8.,  8.],
       [ 9.,  0.],
       [ 5.,  3.],
       [ 3.,  2.]])

In [216]:
a[:,np.newaxis]

array([ 8.,  9.])